/**
 * Calendar Service (Web Version)
 * Web-compatible calendar integration using ICS file downloads
 */

import { createLogger } from './Logger';

const logger = createLogger('CalendarService');

export interface CalendarEvent {
  title: string;
  startDate: Date;
  endDate: Date;
  location?: string;
  notes?: string;
  alarms?: Array<{ relativeOffset: number }>;
}

class CalendarService {
  private static instance: CalendarService;

  private constructor() {}

  public static getInstance(): CalendarService {
    if (!CalendarService.instance) {
      CalendarService.instance = new CalendarService();
    }
    return CalendarService.instance;
  }

  public isSupported(): boolean {
    return typeof window !== 'undefined';
  }

  public async requestPermissions(): Promise<boolean> {
    logger.info('Calendar permissions not required on web');
    return true;
  }

  public async addAppointmentToCalendar(appointment: {
    doctorName: string;
    doctorSpecialty: string;
    date: Date;
    startTime: string;
    duration?: number;
    location?: string;
    consultationFee?: number;
    reason?: string;
  }): Promise<boolean> {
    try {
      const [hours, minutes] = appointment.startTime.split(':').map(Number);
      const startDate = new Date(appointment.date);
      startDate.setHours(hours, minutes, 0, 0);
      
      const duration = appointment.duration || 30;
      const endDate = new Date(startDate.getTime() + duration * 60 * 1000);

      const icsContent = this.generateICS({
        title: `Appointment: Dr. ${appointment.doctorName}`,
        startDate,
        endDate,
        location: appointment.location || `${appointment.doctorSpecialty} Consultation`,
        notes: this.buildEventNotes(appointment),
        alarms: [
          { relativeOffset: -24 * 60 },
          { relativeOffset: -60 },
          { relativeOffset: -15 }
        ]
      });

      if (typeof window !== 'undefined') {
        const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `medibot-appointment-${startDate.getTime()}.ics`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);

        logger.info('Calendar file downloaded', { doctorName: appointment.doctorName });
        return true;
      }
      
      return false;
      
    } catch (_error) {
      logger.error('Error downloading calendar file', _error as Error);
      return false;
    }
  }

  private buildEventNotes(appointment: {
    doctorName: string;
    doctorSpecialty: string;
    reason?: string;
    consultationFee?: number;
  }): string {
    let notes = `Doctor: Dr. ${appointment.doctorName}\n`;
    notes += `Specialty: ${appointment.doctorSpecialty}\n`;
    
    if (appointment.reason) {
      notes += `Reason: ${appointment.reason}\n`;
    }
    
    if (appointment.consultationFee) {
      notes += `Fee: $${appointment.consultationFee}\n`;
    }
    
    notes += '\nGenerated by MediBot';
    
    return notes;
  }

  private generateICS(event: CalendarEvent): string {
    const formatDate = (date: Date): string => {
      return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    };

    let ics = 'BEGIN:VCALENDAR\n';
    ics += 'VERSION:2.0\n';
    ics += 'PRODID:-//MediBot//Healthcare App//EN\n';
    ics += 'CALSCALE:GREGORIAN\n';
    ics += 'METHOD:PUBLISH\n';
    ics += 'BEGIN:VEVENT\n';
    ics += `UID:${Date.now()}@medibot.com\n`;
    ics += `DTSTAMP:${formatDate(new Date())}\n`;
    ics += `DTSTART:${formatDate(event.startDate)}\n`;
    ics += `DTEND:${formatDate(event.endDate)}\n`;
    ics += `SUMMARY:${event.title}\n`;
    
    if (event.location) {
      ics += `LOCATION:${event.location}\n`;
    }
    
    if (event.notes) {
      ics += `DESCRIPTION:${event.notes.replace(/\n/g, '\\n')}\n`;
    }

    if (event.alarms) {
      event.alarms.forEach(alarm => {
        ics += 'BEGIN:VALARM\n';
        ics += 'ACTION:DISPLAY\n';
        ics += `TRIGGER:-PT${Math.abs(alarm.relativeOffset)}M\n`;
        ics += 'DESCRIPTION:Reminder\n';
        ics += 'END:VALARM\n';
      });
    }
    
    ics += 'END:VEVENT\n';
    ics += 'END:VCALENDAR\n';
    
    return ics;
  }

  public async checkPermissions(): Promise<boolean> {
    return true;
  }
}

export const calendarService = CalendarService.getInstance();
export default CalendarService;
